service: email-to-s3
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:STORAGE_REGION, 'us-east-1'}
  environment:
    STORAGE_ENDPOINT: ${env:STORAGE_ENDPOINT}
    STORAGE_REGION: ${env:STORAGE_REGION}
    STORAGE_ACCESS_KEY_ID: ${env:STORAGE_ACCESS_KEY_ID}
    STORAGE_SECRET_ACCESS_KEY: ${env:STORAGE_SECRET_ACCESS_KEY}
    STORAGE_BUCKET: ${env:STORAGE_BUCKET}
    POSTMARK_SERVER_TOKEN: ${env:POSTMARK_SERVER_TOKEN}
    SEND_EMAIL_RESPONSE: ${env:SEND_EMAIL_RESPONSE}
    JWT_SECRET: ${env:JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: arn:aws:s3:::${env:STORAGE_BUCKET}/*

functions:
  emailWebhook:
    handler: src/handler.handler
    timeout: 30
    events:
      - http:
          path: webhooks/email
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
